### ISSUE TITLE
您好, 请问下这个py指标算出来是不是和matlab版的差挺多的.

### ISSUE THREAD

**Issue by aflyingnoob** [mczhuge/SOCToolbox#1]

**Comment by aflyingnoob** [comment]
我跑了下, 发现e-MEASURE差别挺多的QAQ

**Comment by mczhuge** [comment]
请注意是哪个是Mean，Average，还是
Adaptive E-measure。不同一定是有差别的。另外，建议使用[ICON](https://github.com/mczhuge/ICON/tree/main/util/evaltool)里面的。另外，有一些matlab里面的评测不一定对，目前我们确认现在的这一套是没有偏差的。但是总体而言，只要你所有数据在同一个代码下测试，就不会出现不公平的问题。
