### ISSUE TITLE
Some simple but necessary improvement suggestions. 

### ISSUE THREAD

**Issue by Ayews** [mczhuge/SOCToolbox#2]
We have discovered some situations while using the repo, which may help improve its usability. 
1.  Some masks are mixed into the images of the dataset you publish, such as the 'SOC-MB' subset. 
2.  'README.md' provides much guidance, but the structure is chaotic. We suggest that you only provide a concise and clear data preparation method. As you described, using the partitioned dataset directly for prediction is more convenient. 
3.  The published repo only has masks for the SOC-AC subset. We suggest either providing masks for all subsets or explaining this in 'README.md' to guide users in customizing mask paths.

**Comment by mczhuge** [comment]
Thanks! I think the GitHub is simple to read. 

1. It is hard to put all the data into Github Repo. We give part of samples like SOC-AC is to show how to replace the masks.

2. As stated in README.md, ``If you download SOC on above link, you can ignore procedures below.``, we strongly suggest downloading the dataset from  [Baidu | Key: iqul ](https://pan.baidu.com/s/1kWebPUhCQOCsvvAouo7eGQ). Then, you can ignore the two python running in the README.md.

If you have any questions, feel free to let me know.
